This is the prototype of the Mean Field

There will be three main modules:

- 1) Agent

- 2) MeanField

- 3) BlackBoard

In [1]:
from IPython.core.display import display, HTML
display(HTML("<style>.container { width:100% !important; }</style>"))

In [2]:
import numpy as np
import scipy as sp
import ode
from numerical_propagator import *
from synchronizer import *
from blackboard import *
from batteryAgent import *

### batteryAgent

states: 

state 1: $ q_1 $

state 2: $ q_B $

controls:

$u_B$


In [3]:
bb=Blackboard()

In [4]:
bat = batteryAgent(bb, state_indices=[1,2], control_indices=[1])

In [5]:
bat.L_l(1,233,3,4,5,3,4,5,3,3,4,5,3,2,3,4)

-129181.5

In [6]:
bat.H_l(1,233,3,43,5,3,49,59,93,93,4,5,3,21,2,3)

-115894.21082303333

Test q_rhs_H_l_nou, and p_rhs_H_l_nou

In [7]:
np.concatenate([np.array([9]),np.array([10])])

array([ 9, 10])

In [8]:
bat.q_rhs_H_l_nou(1,233,3,43,5,3,49,59,93,93,4,5,3,21,2)

array([ 58, -54])

In [9]:
bat.p_rhs_H_l_nou(1,233,3,43,5,3,49,59,93,93,4,5,3,21,2)

array([-1,  0])

In [10]:
bat.q_rhs_H_l_u(1,233,3,43,5,3,49,59,93,93,4,5,3,21,2)

array([[  0, 230]])

In [11]:
bat.p_rhs_H_l_u(1,233,3,43,5,3,49,59,93,93,4,5,3,21,2)

array([[0, 0]])

In [12]:
bat.q_rhs_H_l(1,233,3,43,5,3,49,59,93,93,4,5,3,21,2,8)

array([ 92, 862])

In [13]:
bat.p_rhs_H_l(1,233,3,43,5,3,49,59,93,93,4,5,3,21,2,8)

array([-11,  10])

In [14]:
bat.qp_rhs_H_l(1,233,3,43,5,3,49,59,93,93,4,5,3,21,2,3)

array([ 92, 859, -11,  10])

### write qp_rhs and write a test for H_D

In [15]:
bat.H_D(2,3,4,1, 2,3,4,1, 2,3,4,1, 2,3,4,1,2,3,4,1)

NameError: global name 'v_c_1' is not defined