This is the prototype of the Mean Field

There will be three main modules:

- 1) Agent

- 2) MeanField

- 3) BlackBoard

In [1]:
from IPython.core.display import display, HTML
display(HTML("<style>.container { width:100% !important; }</style>"))

In [2]:
import numpy as np
import scipy as sp
import ode
from numerical_propagator import *
from synchronizer import *
from blackboard import *
from batteryAgent import *

### batteryAgent

states: 

state 1: $ q_1 $

state 2: $ q_B $

controls:

$u_B$


In [3]:
# fake data
q_1_0=1
q_B_0=1

p_1_0 = 0
p_B_0 = 0

q_s = np.concatenate([np.array([q_1_0]),np.array([q_B_0])])
p_l = np.concatenate([np.array([p_1_0]),np.array([p_B_0])])

u_B = 1

v_c_u_0=1
v_c_1_0=1

c_1=1
R_0=1
R_1=1

v_a=1
Q_0=100
beta=1000
v_N=1

u_vec = np.array([u_B])
lambda_l = np.ones((1,len(q_s))) # must have dimension [1D x state_dim]

# for now, create mean field vectors, and fill in state for other agents with zero.

## building 1 
# states
qfb1 = 0
qab1 = 0
qwb1 = 0
phil1b1 = 0
# controls
u1b1 = 0
u2 = 0
# data
q_w_B1_dot_0 = 0

## building 2
# states
qfb2 = 0
qab2 = 0
qwb2 = 0
phil1b2 = 0
# controls
u1b2 = 0
# data
q_a_B2_dot_0 = 0

## utility
# states
# controls
# no controls for utility because we don't control it
# data
q_u_dot_0=0

# mean field vectors
q_1 = q_1_0
q_B = q_B_0
q_mf = np.array([q_1, q_B, qfb1, qab1, qwb1, phil1b1, qfb2, qab2, qwb2, phil1b2])
u_mf = np.array([u_B, u1b1, u2, u1b2])
# set equal to p_l for now, since we are using fake data 
p_mf = p_l

# parameters
R_a = 0
L_a = 0
K_em = 9

# for extracting values
q_1  = q_mf[0]
q_B  = q_mf[1]
qfb1  = q_mf[2]
qab1  = q_mf[3]
qwb1  = q_mf[4]
phil1b1  = q_mf[5]
qfb2  = q_mf[6]
qab2  = q_mf[7]
qwb2  = q_mf[8]
phil1b2  = q_mf[9]

u_B = u_mf[0]
u1b1 = u_mf[1]
u2 = u_mf[2]
u1b2 = u_mf[3]

u_s = np.array([u_B])
qp_vec = np.concatenate([q_s, p_l, p_mf])

In [4]:
bb = Blackboard()
bat = batteryAgent(bb, state_indices=[1,2], control_indices=[1], q_1_0=q_1_0, q_B_0=q_B_0, v_c_u_0=v_c_u_0, v_c_1_0=v_c_1_0, c_1=c_1, R_0=R_0, R_1=R_1, v_a=v_a, Q_0=Q_0, beta=beta, v_N=v_N, q_u_dot_0=q_u_dot_0, q_a_B2_dot_0 = q_a_B2_dot_0, q_w_B1_dot_0 = q_w_B1_dot_0, L_a =L_a,  R_a =R_a, K_em=K_em)

In [5]:
for v in range(10):
    y='q_1, q_B, qfb1, qab1, qwb1, phil1b1, qfb2, qab2, qwb2, phil1b2'.split(', ')
    print str(str(y[v])+' = q_mf['+str(v)+']')

q_1 = q_mf[0]
q_B = q_mf[1]
qfb1 = q_mf[2]
qab1 = q_mf[3]
qwb1 = q_mf[4]
phil1b1 = q_mf[5]
qfb2 = q_mf[6]
qab2 = q_mf[7]
qwb2 = q_mf[8]
phil1b2 = q_mf[9]


In [6]:
for v in range(4):
    y='u_B, u1b1, u2, u1b2'.split(', ')
    print str(str(y[v])+' = u_mf['+str(v)+']')
    

u_B = u_mf[0]
u1b1 = u_mf[1]
u2 = u_mf[2]
u1b2 = u_mf[3]


In [7]:
bat.L_l(bat.q_s_0, bat.q_s_dot, bat.u_s_0)

-1.5

In [8]:
bat.L_l_q_dot(bat.q_s_0, bat.q_s_dot, bat.u_s_0)

array([0., 0.])

In [9]:
bat.L_mf_q_dot(bat.q_s_0, bat.q_s_dot, bat.u_s_0)

array([0., 0.])

In [10]:
# bat.H_l(1,233,3,43,5,3,49,59,93,93,4,5,3,21,2,3)

Test q_rhs_H_l_nou, and p_rhs_H_l_nou

In [11]:
np.concatenate([np.array([9]),np.array([10])])

array([ 9, 10])

In [12]:
bat.q_rhs_H_l_nou(q_s, p_l, lambda_l)

array([ 1, -3])

In [13]:
bat.p_rhs_H_l_nou(q_s, p_l, lambda_l)

array([0, 0])

In [14]:
bat.q_rhs_H_l_u(q_s, p_l)

array([[0, 0]])

In [15]:
bat.p_rhs_H_l_u(q_s, p_l)

array([[0, 0]])

In [16]:
bat.q_rhs_H_l(q_s, p_l, u_s, lambda_l)

array([ 1, -3])

In [17]:
bat.p_rhs_H_l(q_s, p_l, u_s, lambda_l)

array([0, 0])

In [18]:
bat.qp_rhs_H_l(q_s, p_l, u_s, lambda_l)

array([ 1, -3,  0,  0])

In [19]:
bat.q_rhs_H_mf_u(q_mf, p_mf, u_mf)

array([[1., 1.]])

In [20]:
p_mf

array([0, 0])

In [21]:
bat.p_rhs_H_mf_u(q_mf, p_mf, u_mf) # sanity check it is same dimensions as bat.q_rhs_H_l_u(q_s, p_l)

array([[1., 1.]])

In [22]:
bat.q_rhs_H_mf(q_mf, p_mf, u_mf, u_s)

array([1., 1.])

In [23]:
bat.p_rhs_H_l(q_s, p_l, u_s, lambda_l)

array([0, 0])

In [24]:
bat.p_rhs_H_mf(q_mf, p_mf,u_mf, u_s)

array([1., 1.])

In [25]:
q_mf

array([1, 1, 0, 0, 0, 0, 0, 0, 0, 0])

In [26]:
p_mf

array([0, 0])

In [27]:
bat.qp_rhs_H_mf(q_mf, p_mf, u_mf, u_s)

array([1., 1., 1., 1.])

In [28]:
qp_vec

array([1, 1, 0, 0, 0, 0])

In [29]:
# state_dim=sliding_window_instance.state_dim, Gamma = sliding_window_instance.Gamma, u_0 = u_0, q_mf=q_mf, u_mf=u_mf
# 0.0, qp_vec, state_dim=sliding_window_instance.state_dim, Gamma = sliding_window_instance.Gamma, u_0 = u_0, q_mf=q_mf, u_mf=u_mf
bat.lambda_l = 0
qp_vec = bat.qp_rhs(0.0, qp_vec, state_dim=bat.state_dim, Gamma = bat.Gamma, u_0 = u_s, q_mf=q_mf, u_mf=u_mf, lambda_l=bat.lambda_l)

In [30]:
state_dim=bat.state_dim

q_s_dot, p_l_dot, p_mf_dot = qp_vec[:state_dim], qp_vec[state_dim:state_dim*2], qp_vec[state_dim*2:]

In [31]:
q_s_dot

array([1., 1.])

In [32]:
q_s_dot

array([1., 1.])

In [33]:
p_l_dot


array([-1.,  3.])

In [34]:
p_mf_dot

array([1., 1.])

### write u_rhs , qp_rhs and test with numerical propagator

In [35]:
bat.t_0

0

In [36]:
bat.q_s_dot

array([0., 0.])

In [37]:
bat.q_s_0

array([0., 0.])

In [38]:
q_mf

array([1, 1, 0, 0, 0, 0, 0, 0, 0, 0])

In [39]:
H_l = bat.H_l(q_s, p_l, u_s, lambda_l)

In [40]:
H_l_u = H_l = bat.H_l_u(q_s, p_l)

In [41]:
H_l_nou = bat.H_l_nou(q_s, p_l, u_s)

In [42]:
H_l[0]

0.0

In [43]:
np.shape(q_mf)

(10,)

In [44]:
print q_s_dot

[1. 1.]


In [45]:
# q_s_dot should be returning something of dimension 1 x state_dim.  But instead it is returning something of dimenion 2 d

In [46]:
print stop

NameError: name 'stop' is not defined

In [47]:
# state_dim=sliding_window_instance.state_dim, Gamma = sliding_window_instance.Gamma, u_0 = u_0, q_mf=q_mf, u_mf=u_mf
# 0.0, qp_vec, state_dim=sliding_window_instance.state_dim, Gamma = sliding_window_instance.Gamma, u_0 = u_0, q_mf=q_mf, u_mf=u_mf

# for now
q_mf_dot = q_mf
H_l_D = 1 # H_l
# u_0 = u_B


# p_mf = p_l

# u_s = u_B
p_l = bat.L_l_q_dot(q_s, q_s_dot, u_s)
p_mf = bat.L_mf_q_dot(q_mf, q_mf_dot, u_mf)



In [48]:
p_l

array([2., 3.])

In [49]:
p_mf

array([2, 2])

In [50]:
alpha_mf, alpha_l = alphas(bat, q_mf, p_mf, u_mf, u_s, q_s_dot, q_mf_dot, p_mf_dot, q_s, p_l, H_l_D, p_l_dot)
Beta_mf, Beta_l = Betas(bat, q_mf, p_mf, u_mf, u_s, q_s_dot, q_mf_dot, p_mf_dot, q_s, p_l)

In [51]:
alpha_mf

[0.0]

In [52]:
alpha_l

[0.0]

In [53]:
Beta_mf


[array([8.])]

In [54]:
Beta_l

[array([0.])]

In [55]:
u_dot_vec = bat.u_rhs(0.0, qp_vec, state_dim=state_dim, Gamma = bat.Gamma, qp_vec = qp_vec, u_0=u_s, q_s_dot=q_s_dot, p_l_dot=p_l_dot, p_mf_dot=p_mf_dot, q_mf_dot=q_mf_dot, q_mf=q_mf, u_mf=u_mf, H_l_D=H_l_D, Beta_mf=Beta_mf, Beta_l=Beta_l, alpha_mf=alpha_mf, alpha_l=alpha_l)

KeyError: 'H_mf_D'

In [57]:
u_dot_vec

NameError: name 'u_dot_vec' is not defined

In [58]:
def test_function(a):
    '''
    Need to test the dimensions of the inputs, and also the dimensions of the outputs.
    '''
    assert np.shape(a)==(1,)
    return np.concatenate([a,a])

In [59]:
test_function(np.array([3]))

array([3, 3])

In [60]:
'''
How should we implement this?
1) write a single method called "test_dimensions"
2) it will test each of the methods that we know appear in all of the 
'''

'\nHow should we implement this?\n1) write a single method called "test_dimensions"\n2) it will test each of the methods that we know appear in all of the \n'