This is the prototype of the Mean Field

There will be three main modules:

- 1) Agent

- 2) MeanField

- 3) BlackBoard

In [30]:
from IPython.core.display import display, HTML
display(HTML("<style>.container { width:100% !important; }</style>"))

In [31]:
import numpy as np
import scipy as sp
import ode
from numerical_propagator import *
from synchronizer import *
from blackboard import *
from batteryAgent import *

### batteryAgent

states: 

state 1: $ q_1 $

state 2: $ q_B $

controls:

$u_B$


In [32]:
# fake data
q_1_0=1
q_B_0=1

p_1_0 = 0
p_B_0 = 0

q_s = np.concatenate([np.array([q_1_0]),np.array([q_B_0])])
p_l = np.concatenate([np.array([p_1_0]),np.array([p_B_0])])

u_B = 1

v_c_u_0=1
v_c_1_0=1

c_1=1
R_0=1
R_1=1

v_a=1
Q_0=100
beta=1000
v_N=1

qp_vec = np.concatenate([q_s, p_l])
u_vec = np.array([u_B])

# for now, create mean field vectors, and fill in state for other agents with zero.

## building 1 
# states
qfb1 = 0
qab1 = 0
qwb1 = 0
phil1b1 = 0
# controls
u1b1 = 0
u2 = 0

## building 2
# states
qfb2 = 0
qab2 = 0
qwb2 = 0
phil1b2 = 0
# controls
u1b2 = 0

# mean field vectors

q_mf = 
u_mf = 

In [33]:
bb = Blackboard()

In [5]:
bat = batteryAgent(bb, state_indices=[1,2], control_indices=[1], q_1_0=q_1_0, q_B_0=q_B_0, v_c_u_0=v_c_u_0, v_c_1_0=v_c_1_0, c_1=c_1, R_0=R_0, R_1=R_1, v_a=v_a, Q_0=Q_0, beta=beta, v_N=v_N)

In [6]:
bat.L_l(bat.q_s_0, bat.q_s_dot, bat.u_s_0)

array([-1.5])

In [7]:
bat.L_l_q_dot(bat.q_s_0, bat.q_s_dot, bat.u_s_0)

array([0., 0.])

In [8]:
bat.H_l(1,233,3,43,5,3,49,59,93,93,4,5,3,21,2,3)

-115894.21082303333

Test q_rhs_H_l_nou, and p_rhs_H_l_nou

In [9]:
np.concatenate([np.array([9]),np.array([10])])

array([ 9, 10])

In [10]:
bat.q_rhs_H_l_nou(1,233,3,43,5,3,49,59,93,93,4,5,3,21,2)

array([ 58, -54])

In [11]:
bat.p_rhs_H_l_nou(1,233,3,43,5,3,49,59,93,93,4,5,3,21,2)

array([-1,  0])

In [12]:
bat.q_rhs_H_l_u(1,233,3,43,5,3,49,59,93,93,4,5,3,21,2)

array([[  0, 230]])

In [13]:
bat.p_rhs_H_l_u(1,233,3,43,5,3,49,59,93,93,4,5,3,21,2)

array([[0, 0]])

In [14]:
bat.q_rhs_H_l(1,233,3,43,5,3,49,59,93,93,4,5,3,21,2,8)

array([ 92, 862])

In [15]:
bat.p_rhs_H_l(1,233,3,43,5,3,49,59,93,93,4,5,3,21,2,8)

array([-11,  10])

In [16]:
bat.qp_rhs_H_l(1,233,3,43,5,3,49,59,93,93,4,5,3,21,2,3)

array([ 92, 859, -11,  10])

In [17]:
bat.q_rhs_H_mf_u(2,3,4,1, 2,3,4,1, 2,3,4,1, 2,3,4)

array([[0, 0]])

In [18]:
bat.p_rhs_H_mf_u(3,4,1, 2,3,4,1, 2,3,4,1, 2,3,4,1)

array([[0, 0]])

In [19]:
bat.q_rhs_H_mf(2,3,4,1, 2,3,4,1, 2,3,4,1, 2,3,4,1)

array([ 3, -1])

In [20]:
bat.p_rhs_H_l(2,3,4,1, 2,3,4,1, 2,3,4,1, 2,3,4,1)

array([ 3, -1])

In [21]:
bat.p_rhs_H_l_u(2,3,4,1, 2,3,4,1, 2,3,4,1, 2,3,4)

array([[0, 0]])

In [22]:
bat.q_rhs_H_l_u(2,3,4,1, 2,3,4,1, 2,3,4,1, 2,3,4)

array([[0, 0]])

In [23]:
bat.p_rhs_H_l_nou(2,3,4,1, 2,3,4,1, 2,3,4,1, 2,3,4)

array([-1, -1])

In [ ]:
bat.q_rhs_H_mf(2,3,4,1, 2,3,4,1, 2,3,4,1, 2,3,4,3)

In [ ]:
bat.qp_rhs(2,3,4,1, 2,3,4,1, 2,3,4,1, 2,3,4,3)

### write u_rhs , qp_rhs and test with numerical propagator

In [34]:
# What things need to call qp_rhs?
'''
Need to fit everything into these inputs:
qp_vec, state_dim=sliding_window_instance.state_dim, Gamma = sliding_window_instance.Gamma, u_0 = u_0, q_mf=q_mf, u_mf=u_mf
'''

'\nNeed to fit everything into these inputs:\nqp_vec, state_dim=sliding_window_instance.state_dim, Gamma = sliding_window_instance.Gamma, u_0 = u_0, q_mf=q_mf, u_mf=u_mf\n'

In [35]:
# propagate_q_p(qpu_vec, t_start, t_end, sliding_window_instance, q_mf, u_mf):

In [36]:
# for right now, doesn't matter what we fill in for the values of the states of the other agents, so for now make =0
u_0 = [u_B]
q_mf = [q_B, q_1, q_1_a, q_1_f, q_1_w, phi_L_1, q_2_a, q_2_f, q_2_w, phi_2_L]
u_mf = [u_B, u_1_1, u_1_2, u_2_1]

NameError: name 'q_B' is not defined

In [37]:
'''remember that the propagator must stay generalized!  cannot hardcode that'''

'remember that the propagator must stay generalized!  cannot hardcode that'

In [39]:
bat.t_0

0

In [40]:
bat.q_s_dot

array([0., 0.])

In [41]:
bat.q_s_0

array([0., 0.])

In [42]:
sliding_window(bat)

AttributeError: batteryAgent instance has no attribute 'L_l_D_q_Dot'