This is the prototype of the Mean Field

There will be three main modules:

- 1) Agent

- 2) MeanField

- 3) BlackBoard

In [1]:
from IPython.core.display import display, HTML
display(HTML("<style>.container { width:100% !important; }</style>"))

In [2]:
import numpy as np
import scipy as sp
import ode
from numerical_propagator import *
from synchronizer import *
from blackboard import *
from batteryAgent import *

### batteryAgent

states: 

state 1: $ q_1 $

state 2: $ q_B $

controls:

$u_B$


In [3]:
# fake data
q_1_0=1
q_B_0=1

p_1_0 = 0
p_B_0 = 0

q_s = np.concatenate([np.array([q_1_0]),np.array([q_B_0])])
p_l = np.concatenate([np.array([p_1_0]),np.array([p_B_0])])

u_B = 1

v_c_u_0=1
v_c_1_0=1

c_1=1
R_0=1
R_1=1

v_a=1
Q_0=100
beta=1000
v_N=1

qp_vec = np.concatenate([q_s, p_l])
u_vec = np.array([u_B])

# for now, create mean field vectors, and fill in state for other agents with zero.

## building 1 
# states
qfb1 = 0
qab1 = 0
qwb1 = 0
phil1b1 = 0
# controls
u1b1 = 0
u2 = 0

## building 2
# states
qfb2 = 0
qab2 = 0
qwb2 = 0
phil1b2 = 0
# controls
u1b2 = 0

# mean field vectors

q_mf = np.array([q_1_0, q_B_0, qfb1, qab1, qwb1, phil1b1, qfb2, qab2, qwb2, phil1b2])
u_mf = np.array([u_B, u1b1, u2, u1b2])

In [4]:
bb = Blackboard()

In [5]:
bat = batteryAgent(bb, state_indices=[1,2], control_indices=[1], q_1_0=q_1_0, q_B_0=q_B_0, v_c_u_0=v_c_u_0, v_c_1_0=v_c_1_0, c_1=c_1, R_0=R_0, R_1=R_1, v_a=v_a, Q_0=Q_0, beta=beta, v_N=v_N)

In [6]:
bat.L_l(bat.q_s_0, bat.q_s_dot, bat.u_s_0)

array([-1.5])

In [7]:
bat.L_l_q_dot(bat.q_s_0, bat.q_s_dot, bat.u_s_0)

array([0., 0.])

In [8]:
bat.H_l(1,233,3,43,5,3,49,59,93,93,4,5,3,21,2,3)

-115894.21082303333

Test q_rhs_H_l_nou, and p_rhs_H_l_nou

In [9]:
np.concatenate([np.array([9]),np.array([10])])

array([ 9, 10])

In [10]:
bat.q_rhs_H_l_nou(1,233,3,43,5,3,49,59,93,93,4,5,3,21,2)

array([ 58, -54])

In [11]:
bat.p_rhs_H_l_nou(1,233,3,43,5,3,49,59,93,93,4,5,3,21,2)

array([-1,  0])

In [12]:
bat.q_rhs_H_l_u(1,233,3,43,5,3,49,59,93,93,4,5,3,21,2)

array([[  0, 230]])

In [13]:
bat.p_rhs_H_l_u(1,233,3,43,5,3,49,59,93,93,4,5,3,21,2)

array([[0, 0]])

In [14]:
bat.q_rhs_H_l(1,233,3,43,5,3,49,59,93,93,4,5,3,21,2,8)

array([ 92, 862])

In [15]:
bat.p_rhs_H_l(1,233,3,43,5,3,49,59,93,93,4,5,3,21,2,8)

array([-11,  10])

In [16]:
bat.qp_rhs_H_l(1,233,3,43,5,3,49,59,93,93,4,5,3,21,2,3)

array([ 92, 859, -11,  10])

In [17]:
bat.q_rhs_H_mf_u(2,3,4,1, 2,3,4,1, 2,3,4,1, 2,3,4)

array([[0, 0]])

In [18]:
bat.p_rhs_H_mf_u(3,4,1, 2,3,4,1, 2,3,4,1, 2,3,4,1)

array([[0, 0]])

In [19]:
bat.q_rhs_H_mf(2,3,4,1, 2,3,4,1, 2,3,4,1, 2,3,4,1)

array([ 3, -1])

In [20]:
bat.p_rhs_H_l(2,3,4,1, 2,3,4,1, 2,3,4,1, 2,3,4,1)

array([ 3, -1])

In [21]:
bat.p_rhs_H_l_u(2,3,4,1, 2,3,4,1, 2,3,4,1, 2,3,4)

array([[0, 0]])

In [22]:
bat.q_rhs_H_l_u(2,3,4,1, 2,3,4,1, 2,3,4,1, 2,3,4)

array([[0, 0]])

In [23]:
bat.p_rhs_H_l_nou(2,3,4,1, 2,3,4,1, 2,3,4,1, 2,3,4)

array([-1, -1])

In [24]:
bat.q_rhs_H_mf(2,3,4,1, 2,3,4,1, 2,3,4,1, 2,3,4,3)

array([ 3, -1])

In [33]:
# state_dim=sliding_window_instance.state_dim, Gamma = sliding_window_instance.Gamma, u_0 = u_0, q_mf=q_mf, u_mf=u_mf
# 0.0, qp_vec, state_dim=sliding_window_instance.state_dim, Gamma = sliding_window_instance.Gamma, u_0 = u_0, q_mf=q_mf, u_mf=u_mf

qp_vec = bat.qp_rhs(0.0, qp_vec, state_dim=bat.state_dim, Gamma = bat.Gamma, u_0 = u_B, q_mf=q_mf, u_mf=u_mf)

In [35]:
state_dim=bat.state_dim
q_s_dot, p_l_dot, p_mf_dot = qp_vec[:state_dim], qp_vec[state_dim:state_dim*2], qp_vec[state_dim*2:]

In [36]:
q_s_dot

array([-5,  4])

In [37]:
p_l_dot

array([0, 4])

In [38]:
p_mf_dot

array([ 0, -4])

### write u_rhs , qp_rhs and test with numerical propagator

In [26]:
bat.t_0

0

In [27]:
bat.q_s_dot

array([0., 0.])

In [28]:
bat.q_s_0

array([0., 0.])

In [29]:
sliding_window(bat)

AttributeError: batteryAgent instance has no attribute 'L_l_D_q_Dot'