This is v1 of the control law propagator
There will be three main modules:

- 1) Propagator

- 2) sliding window

- 3) window filter

In [1]:
import numpy as np
import scipy as sp
import ode

In [2]:
# Inputs:
q_0 = np.array([0,2])
p_0 = np.array([1,4])
u_0 = np.array([2])

t_start = 0
t_end =  1

integrateTol = 10**-3
integrateMaxIter = 4
state_dim = 2
Gamma = 1


In [3]:
np.ones(np.shape(q_0))

array([1., 1.])

In [4]:
def H_T_p(q,p,u):
    # for q-dot
    return np.ones(np.shape(q))

def H_T_q(q,p,u):
    # for p-dot
    return np.ones(np.shape(p))
    
def Q_u(q,p,u):
    # for u-dot
    return np.ones(np.shape(u))
    

In [5]:
def rhs(t, qpu_vec, **kwargs):
    '''
    Input: qpu_vec
    
    Output: qpu_vec
    '''
    state_dim = kwargs['state_dim']
    Gamma = kwargs['Gamma']
    q = qpu_vec[:state_dim]
    p = qpu_vec[state_dim:2*state_dim]
    u = qpu_vec[2*state_dim:]
    q_dot =  H_T_p(q,p,u)
    p_dot = -1*H_T_q(q,p,u)
    u_dot = -Gamma*Q_u(q,p,u)
#     import pdb; pdb.set_trace()
    return np.hstack([q_dot, p_dot, u_dot])

In [6]:
print np.hstack([q_0, p_0, u_0])[2:]
print np.hstack([q_0, p_0, u_0])[2:2*2]
print np.hstack([q_0, p_0, u_0])

[1 4 2]
[1 4]
[0 2 1 4 2]


In [7]:
# call the ode to integrate the dynamic equations to get q, p, and u

ODE takes as input:
- RHS
- initial condition
- t_start and t_end for which you want your desired output values

In [8]:
#     q = qpu_vec[:state_dim]
#     p = qpu_vec[state_dim:2*state_dim]
#     u = qpu_vec[2*state_dim:]

In [9]:
qpu_vec = np.hstack([q_0, p_0, u_0])

In [ ]:
qpu_vec 

array([0, 2, 1, 4, 2])

In [ ]:
# qpu_vec = np.vstack([q_0, p_0, u_0])
ode.ode_rk23(rhs, t_start, t_end, qpu_vec, integrateTol, integrateMaxIter, state_dim=state_dim, Gamma = Gamma)

> /Users/jordan/Documents/Atigeo/cdi/control_law_propagator/ode.py(108)ode_rk23()
-> R = abs((-5.0*k1+6.0*k2+8.0*k3-9.0*k4)*hStep)/72.0
(Pdb) n
> /Users/jordan/Documents/Atigeo/cdi/control_law_propagator/ode.py(111)ode_rk23()
-> R1 = max(R/yscale)
(Pdb) n
> /Users/jordan/Documents/Atigeo/cdi/control_law_propagator/ode.py(112)ode_rk23()
-> R2 = R1/tol
(Pdb) n
> /Users/jordan/Documents/Atigeo/cdi/control_law_propagator/ode.py(115)ode_rk23()
-> if (R2 < 1):
(Pdb) n
> /Users/jordan/Documents/Atigeo/cdi/control_law_propagator/ode.py(117)ode_rk23()
-> t = t+hStep
(Pdb) n
> /Users/jordan/Documents/Atigeo/cdi/control_law_propagator/ode.py(118)ode_rk23()
-> y1 = k40
(Pdb) n
> /Users/jordan/Documents/Atigeo/cdi/control_law_propagator/ode.py(119)ode_rk23()
-> k1 = k4
(Pdb) n
> /Users/jordan/Documents/Atigeo/cdi/control_law_propagator/ode.py(120)ode_rk23()
-> tTime = np.append(tTime, t)
(Pdb) n
> /Users/jordan/Documents/Atigeo/cdi/control_law_propagator/ode.py(121)ode_rk23()
-> y = np.row_stack((y