This is the prototype of the Mean Field

There will be three main modules:

- 1) Agent

- 2) MeanField

- 3) BlackBoard

In [40]:

import numpy as np
import scipy as sp
import ode
from sliding_window import *

### Agent

In [41]:
myAgent.qpu_vec

array([0, 0, 0, 0])

In [45]:
# print len(self.state_indices) == self.state_dim 
# print len(self.qpu_vec) == 3*self.state_dim + len(self.control_indices)


In [46]:
print myAgent.q_l_0
print myAgent.p_l_0

[0]
[0]


In [47]:
print myAgent.p_mf_0

[0]


In [48]:
q_l_0 = np.array([0,1])
p_l_0 = np.array([0,3])
p_mf_0 = np.array([0,4])
u_0 = np.array([0,2])
qpu_vec = np.hstack([q_l_0, p_l_0, p_mf_0, u_0])


In [49]:
qpu_vec

array([0, 1, 0, 3, 0, 4, 0, 2])

In [97]:
class Agent:
    
    def __init__(self, mean_field, blackboad, state_indices, control_indices):
        '''
        state_indices (list of integers): This list tells which states pertain to this agent. e.g. [1,2] would 
        tell us that states 1 and 2 pertain to this agent.
        
        A word on notation:  The notation used for the methods of the agent is:  
            - If it is a partial derivative: <denominator>_rhs_H_<type of hamiltonian (l, mf, or s)>_<nou or u>.  e.g., 
            "qp_rhs_H_l_u" denotes the partial derivative with respect to q and p of the terms in the local Hamiltonian that contain control variables.
            - If it is a hamiltonian: H_<type of hamiltonian (l, mf, or s)>_<nou or u>.  e.g. "H_mf_nou" denotes the mean field hamiltonian
            with terms not containing u.
        '''
        self.state_indices = state_indices
        self.control_indices = control_indices
        self.mf = mean_field
        self.bb = blackboard
        self.u_l_vec = None
        self.qp_l_vec = None
        self.u_l_dict = None
        self.qp_l_dict = None

        # Inputs for numerical propagator
        # qp_vec is going to be [q_l, p_l, p_mf], so it will have dimension = 3*state_dim

        self.q_l_0 = np.array([0])
        self.p_l_0 = np.array([0])
        self.p_mf_0 = np.array([0])
        self.u_0 = np.array([0])
        self.qpu_vec = np.hstack([self.q_l_0, self.p_l_0, self.p_mf_0, self.u_0])
        self.state_dim = 1
        self.Gamma = 1 
        self.gamma = 1

        # Inputs for numerical integration
        self.integrateTol = 10**-3
        self.integrateMaxIter = 40

        # Inputs for sliding window
        self.t_0 = 0 
        self.T =  2
        self.K=1 

        self.t_terminal = 2
        self.n_s = 10

        self.validate_dimensions()

    def validate_dimensions(self):
        # TODO: move to parent class "SlidingWindow"
        assert len(self.state_indices) == self.state_dim, 'state dimensions are not consistent.  dimension of state indices is '+str(len(self.state_indices)) +' and state_dim is '+str(self.state_dim)
        assert len(self.control_indices) == len(self.u_0), 'control dimensions are not consistent.  dimension of control_indices is '+str(len(self.control_indices)) +' and len(u_0) is '+str(len(self.u_0))
        assert len(self.qpu_vec) == 3*self.state_dim + len(self.control_indices), ' control and state dimensions are not consistent with qpu_vec : length of qpu_vec is '+str(len(self.qpu_vec))+ ' and 3*self.state_dim + len(self.control_indices) is ' + str(3*self.state_dim + len(self.control_indices))
    
    '''
    TODO:  
    Add an assertion to check that the dimension of q_l_0, p_mf_0, and u_0:
        - the dimension of state_dim    
        - state_indices and control_indices set upon initiation of the Agent
        - 
    '''
    
    def L_l(self, q, q_dot, u):
        return
    
    def L_l_q_dot(self, t, q, q_dot, u, **kwargs):
        return
    
    def H_l_nou(self, q, p, lambda_l):
        return 

    def qp_rhs_H_l_nou(self, t, qp_vec, **kwargs):
        dim = len(qp_vec)/2
        q = qp_vec[:dim]
        p = qp_vec[dim:2*dim]
        u = kwargs['u_0']
        # for q-dot
        q_dot =  np.zeros(np.shape(p))
        # for p-dot
        p_dot =  np.zeros(np.shape(q))
        q_D_dot = np.zeros(np.shape(p))
        p_D_dot = np.zeros(np.shape(q))
        return np.concatenate([q_dot, p_dot, q_D_dot, p_D_dot])
       
    def u_rhs_H_l_nou(self, t, u_vec, **kwargs):
        qp_vec = kwargs['qp_vec']
        dim = len(qp_vec)/4
        q = qp_vec[:dim]
        p = qp_vec[dim:2*dim]
        q_D = qp_vec[2*dim:3*dim]
        p_D = qp_vec[3*dim:]
        Gamma = kwargs['Gamma']
        # for u-dot
        returnurn -1*Gamma*np.zeros(np.shape(u_vec))

    def H_l_u(self, q, p, u):
        return 
    
    def qp_rhs_H_l_u(self, t, qp_vec, **kwargs):
        dim = len(qp_vec)/4
        q = qp_vec[:dim]
        p = qp_vec[dim:2*dim]
        q_D = qp_vec[2*dim:3*dim]
        p_D = qp_vec[3*dim:]
        u = kwargs['u_0']
        # for q-dot
        q_dot =  np.zeros(np.shape(p))
        # for p-dot
        p_dot =  np.zeros(np.shape(q))
        q_D_dot =  np.zeros(np.shape(p))
        p_D_dot =  np.zeros(np.shape(q))
        return np.concatenate([q_dot, p_dot, q_D_dot, p_D_dot])
       
    def u_rhs_H_l_u(self, t, u_vec, **kwargs):
        qp_vec = kwargs['qp_vec']
        dim = len(qp_vec)/4
        q = qp_vec[:dim]
        p = qp_vec[dim:2*dim]
        q_D = qp_vec[2*dim:3*dim]
        p_D = qp_vec[3*dim:]
        Gamma = kwargs['Gamma']
        # for u-dot
        return -1*Gamma*np.zeros(np.shape(u_vec))

#     def qp_rhs_H_s_nou(self, t, qp_vec, **kwargs):
#         # This will include a term for qp_rhs_l and a term for qp_rhs_MF
#         # kwargs should have quenched values
#         qp_vec_quenched = self.bb.construct_q_p(qp_vec, self)
#         # yes it is really slow, but we read from blackboard every time we evaluate this
#         qp_rhs_H_s = (1-alpha)*self.qp_rhs_H_l_nou(qp_vec) + alpha*mf.qp_rhs_H_mf_nou(qp_vec)
#         # must return result in qp_vec format because ode rk23 will call this
#         # qp_rhs_H_s should look like this: np.concatenate([q_dot, p_dot, q_D_dot, p_D_dot])
#         return qp_rhs_H_s
       
#     def qp_rhs_H_s_u(self, t, qp_vec, **kwargs):
#         # This will include a term for qp_rhs_l and a term for qp_rhs_MF: 
#         qp_rhs_H_s = (1-alpha)*qp_rhs_l(self, qp_vec) + alpha*qp_rhs_MF()
#         return np.concatenate([q_dot, p_dot, q_D_dot, p_D_dot])
       
#     def u_rhs_H_s_nou(self, t, u_vec, **kwargs):
#         # This will include a term for qp_rhs_l and a term for qp_rhs_MF: 
#         Gamma = kwargs['Gamma']
#         # for u-dot
#         return -1*Gamma*np.zeros(np.shape(u_vec))

#     def u_rhs_H_s_u(self, t, u_vec, **kwargs):
#         # This will include a term for qp_rhs_l and a term for qp_rhs_MF: 
#         return np.concatenate([q_dot, p_dot, q_D_dot, p_D_dot])
#         Gamma = kwargs['Gamma']
#         # for u-dot
#         return -1*Gamma*np.zeros(np.shape(u_vec))

    def H_l_D():
        pass
        
    def L_l_D():
        pass
        
    def L_l_D_q_Dot():
        pass

    def qp_rhs(self, t, qp_vec, **kwargs):
        # u_l is constant (because of causality, remember?)
        u_l = kwargs['u_0']
        state_dim = kwargs['state_dim']
        q_l = qp_vec[:state_dim]
        p_l = qp_vec[state_dim:2*state_dim]
        p_mf = qp_vec[2*state_dim:]

        qp_rhs_H_mf = self.mf.qp_rhs_H_mf(q_l, p_mf, p_l, u_l)
        
        p_rhs_H_mf = qp_rhs_H_mf[:state_dim]
        q_rhs_H_mf = qp_rhs_H_mf[state_dim:]
        
        qp_rhs_H_l = self.qp_rhs_H_l(q_l, p_l, u_l)
        q_rhs_H_l = qp_rhs_H_l[:state_dim]
        p_rhs_H_l = qp_rhs_H_l[state_dim:]
        
        q_l_dot = self.gamma*q_rhs_H_mf + (1-self.gamma)*q_rhs_H_l
        p_mf_dot = p_rhs_H_mf
        p_l_dot = -1*p_rhs_H_l
        
        return np.concatenate([q_l_dot, p_l_dot, p_mf_dot])
    
    def qp_rhs_H_l(self, q_l, p_l, u_l):
        q_rhs_H_l = self.q_rhs_H_l(q_l, p_l, u_l)
        p_rhs_H_l = self.p_rhs_H_l(q_l, p_l, u_l)
        return [q_rhs_H_l, p_rhs_H_l]
        
    def p_rhs_H_l(self, q_l, p_l, u_l):
        q_l_dot =  q_l, p_l, u_l 
        return q_l_dot
    
    def q_rhs_H_l(self, q_l, p_l, u_l):
        p_l_dot =  q_l + p_l + u_l
        return p_l_dot
    
    def u_rhs(self, t, u_vec, **kwargs):
        return -1*self.Gamma*np.zeros(np.shape(u_vec)) 



In [98]:
blackboard = Blackboard()
mean_field = MeanField()

myAgent=Agent(mean_field, blackboard, state_indices=[1], control_indices=[1])

## MeanField

In [80]:
class MeanField:
    
    def __init__(self):
        pass
    
    def H_MF_nou(self, q, p):
        pass

    def H_MF_u(self, q, p):
        pass
        
    def qp_rhs_H_mf(self, q_l, p_mf, p_l, u_l):
        # remember that we want to propagate as much as possible together in the same rhs function for numerical purposes
        # remember that q_rhs here is w.r.t p_mf but p_rhs here is w.r.t q_l
        q_H_mf_dot = self.p_rhs_H_mf(q_l, p_mf, p_l, u_l)
        p_H_mf_dot = self.q_rhs_H_mf(q_l, p_mf, u_l)
        return np.concatenate([q_H_mf_dot, p_H_mf_dot])
    
    def q_rhs_H_mf(self, q_l, p_mf, u_l):
        p_H_mf_dot = self.q_rhs_H_mf_nou(q_l, p_mf) + sum(self.q_rhs_H_mf_u(q_l, p_mf)*u for i,j in zip())
        return p_H_mf_dot
        
    def q_rhs_H_mf_u(self, q_l, p_mf):
        # there should be one ofthese for each control variable
        p_H_mf_u_dot_1 = q_l + p_mf # or something
#         p_H_mf_u_dot_2 = q_l[1] + p_mf[1] # or something
        return np.concatenate([p_H_mf_u_dot_1]) #, p_H_mf_u_dot_2])
    
    def p_rhs_H_mf(self, q_l, p_mf, p_l, u_l):
        return self.p_rhs_H_mf_nou(q_l, p_mf) + sum([self.p_rhs_H_mf_u(q_l, p_mf)*u for i,j in zip()])

    def p_rhs_H_mf_nou(self, q_l, p_mf):
        return q_l+p_mf # or something

    def q_rhs_H_mf_nou(self, q_l, p_mf):
        p_H_mf_nou_dot_1 = q_l + p_mf
#         p_H_mf_nou_dot_2 = q_l[1] + p_mf[1] # this line is the problem
        return np.concatenate([p_H_mf_nou_dot_1]) #, p_H_mf_nou_dot_2])

#     def p_rhs_H_mf_nou(self, t, qp_vec, **kwargs):
#         # first find out if this needs to be a RHS function, or if it is only called internally.
    
    def p_rhs_H_mf_u():
        pass
          

In [81]:
a=[3,5,2]
b=[2]
g=[a,b]
set([x for g_i in g for x in g_i])

{2, 3, 5}

In [82]:
class Synchronizer:
    
    def __init__(self, agents, blackboard):
        self.agents = agents  # list of all agents.  list with elements of class Agent
        self.bb = blackboard  # instance of class blackboard  
    
    def synchronize():
        # run synchronization
        for agent in self.agents:
            '''     
            1) run synchronized propagation - I think we only need one Agent instead of SlidingWindow now

            For each of the above 2 steps:
                - create sliding window instance
                - call "propagate_dynamics" on the sliding window instance

            get quenched values from blackboard
            '''
            # determine dimensions of p_l and p_MF, and then create
            # dimensions of p_l are determined by number of states for this agent 
            # dimensions of p_MF 
            state_dim_l = len(agent.state_indices)
            # set difference between all states in all agents, and states in current agent
            state_dim_mf = set([agent_i.state_indices for agent_i in self.agents for agent_i.state_indices in agent_i]) - set(agent.state_indices)
            # run propagation with keyword arguments state_dim_l, state_dim_mf
#             agent.sliding_window = 
            qp_vec = self.bb.construct_q_p(agent) # quench the necessary values to be quenched
            qp_vec = qp_rhs_H_s_nou(qp_vec)

### Blackboard

In [83]:
class Blackboard:
    
    def __init__(self):
        '''
#         state_agent_mapping is dictionary with keys: object of class Agent, 
#               values: list of integers state_indices state_indices
        '''
#         self.state_agent_mapping={}
        '''       
        q_p_u_dict is a dictionary which maps 'q', 'p', 'u', to a dictionary of index-value pairs: local values for q, p, and u for this agent.  
                        blackboard holds all of the most recent local values, e.g.
                        {'q': {'1':3, '2':0}, 'p': {'1':3, '2': 2}, 'u': {'1': 0}}
                        It doesn't care which agent updated them most recently.  It only needs to know which values to update.
        q_p_u_dict initially will be filled 
        '''
        self.q_p_u_dict={'q':{}, 'p':{}, 'u':{}}
        self.agents=[]
    
    def construct_p_q(self, agent):
        '''
        Inputs:
            agent (instance of class Agent): This is the agent for which we are constructing p and q.
        
        Outputs:
            q_p_u_dict (dictionary): This dictionary holds all of the q, p, and u values for all of the agents
        '''
        assert agent in self.agents, 'this agent\'s values have not been added to the blackboard.  please call "self.update_q_p_u_dict(<agent>)" before calling this method'
        q_p_u_dict = {'q':{}, 'p':{}, 'u':{}}
        # find which states pertain to this agent
        # for the states that don't, get the values from q_p_u_dict and put them into qp_vec
        for state_ix in agent.state_indices:
            q_p_u_dict['q'][str(state_ix)] = self.q_p_u_dict['q'][str(state_ix)]
            q_p_u_dict['p'][str(state_ix)] = self.q_p_u_dict['p'][str(state_ix)]

        for control_ix in agent.control_indices:
            q_p_u_dict['u'][str(control_ix)] = self.q_p_u_dict['u'][str(control_ix)]

        # for state indices which are not part of agent.state_indices, fill in from blackboard q_p_u_dict
        assert len(set([str(x) for x in agent.control_indices]) - set(self.q_p_u_dict['u'].keys())) == 0, ' there should not be any controls in agent that are not in blackboard '
        assert len(set([str(x) for x in agent.state_indices]) - set(self.q_p_u_dict['q'].keys())) == 0, ' there should not be any states in agent that are not in blackboard '

        # blackboard - agent
        quenched_state_indices = set([str(x) for x in agent.state_indices]) - set(self.q_p_u_dict['q'].keys())
        # fill in with values from blackboard
        for state_ix in quenched_state_indices:
            q_p_u_dict['q'][str(state_ix)] = self.q_p_u_dict['q'][str(state_ix)]
            q_p_u_dict['p'][str(state_ix)] = self.q_p_u_dict['p'][str(state_ix)]
            
        return q_p_u_dict
    
    def update_q_p_u_dict(self, agent):
        '''  This method should be called after local propagation of each agent
        Inputs:
            agent (instance of class Agent): this is the agent whos values we are updating
        Outputs:
            No outputs.  This method just updates the attributes of the blackboard,
            just update the dictionary, agent_q_p_u_dict.
        '''
        # determine which states pertain to this agent and replace the old values with new
        # assert that the number of states is same as number of costates:
        assert len(agent.q_p_u_dict['q']) == len(agent.q_p_u_dict['p']), 'Number of states is not same as number of costates'
        
        for state_ix in agent.state_indices:
            self.q_p_u_dict['q'][str(state_ix)] = agent.q_p_u_dict['q'][str(state_ix)]
            self.q_p_u_dict['p'][str(state_ix)] = agent.q_p_u_dict['p'][str(state_ix)]
            
        for control_ix in agent.control_indices:
            self.q_p_u_dict['u'][str(control_ix)] = agent.q_p_u_dict['u'][str(control_ix)]
        self.agents.append(agent)
    # Look at what things the Blackboard needs
    # It at least needs a mapping that tells which states pertain to which agent
    # It needs to keep track of all states, costates, controls for all agents so that we can plug in values when necessary

#### small test for one agent

In [84]:
blackboard = Blackboard()
mean_field = MeanField()

myAgent=Agent(mean_field, blackboard, state_indices=[1,2], control_indices=[1,2])
myAgent.q_p_u_dict={}
myAgent.q_p_u_dict['q']={}
myAgent.q_p_u_dict['q']['1']=0
myAgent.q_p_u_dict['q']['2']=1

myAgent.q_p_u_dict['p']={}
myAgent.q_p_u_dict['p']['1']=0
myAgent.q_p_u_dict['p']['2']=1

myAgent.q_p_u_dict['u']={}
myAgent.q_p_u_dict['u']['1']=0
myAgent.q_p_u_dict['u']['2']=1

bb=Blackboard()

AssertionError:  control dimensions and state are not consistent with qpu_vec : length of qpu_vec is 4 and 3*self.state_dim + len(self.control_indices) is 8

In [8]:
bb.update_q_p_u_dict(myAgent)

In [9]:
bb.q_p_u_dict

{'p': {'1': 0, '2': 1}, 'q': {'1': 0, '2': 1}, 'u': {'1': 0, '2': 1}}

In [10]:
print myAgent.control_indices
print myAgent.state_indices

[1, 2]
[1, 2]


In [11]:
bb.q_p_u_dict

{'p': {'1': 0, '2': 1}, 'q': {'1': 0, '2': 1}, 'u': {'1': 0, '2': 1}}

In [12]:
q_p_u_dict = bb.construct_p_q(myAgent)

In [13]:
q_p_u_dict

{'p': {'1': 0, '2': 1}, 'q': {'1': 0, '2': 1}, 'u': {'1': 0, '2': 1}}

### Try a very small test

Steps to test qp_rhs and u_rhs:

- Give some arbitrary initial conditions
- create Agent
- create Blackboard
- create MeanField
- connect those three things above.
- somehow create a sliding window instance, or at least wrangle the Agent into a Sliding Window instance

In [19]:
blackboard = Blackboard()
mean_field = MeanField()

myAgent=Agent(mean_field, blackboard, state_indices=[1,2], control_indices=[1,2])
myAgent.q_p_u_dict={}
myAgent.q_p_u_dict['q'] = {}
myAgent.q_p_u_dict['q']['1'] = 0
myAgent.q_p_u_dict['q']['2'] = 1

myAgent.q_p_u_dict['p'] = {}
myAgent.q_p_u_dict['p']['1'] = 0
myAgent.q_p_u_dict['p']['2'] = 1

myAgent.q_p_u_dict['u']={}
myAgent.q_p_u_dict['u']['1'] = 0
myAgent.q_p_u_dict['u']['2'] = 1

In [20]:
# forgot to pass in 'u_l' as a keyword argument
qpu_vec, q_ls_bar, p_ls_bar, p_mfs_bar, u_bar, q_ls, p_ls, p_mfs, us = propagate_dynamics(myAgent)

In [21]:
qpu_vec, q_ls_bar, p_ls_bar, p_mfs_bar, u_bar, q_ls, p_ls, p_mfs, us

(array([0., 0., 0., 0.]),
 array([0.]),
 array([0.]),
 array([0.]),
 array([0.]),
 [array([0.])],
 [array([0.])],
 [array([0.])],
 [array([0.])])

Testing plan:
    - Test this on a few nonzero inputs
    - Test this on multidimensional state
    - Test this on multidimensional control
    - Get this working for multiple agents